enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
adorn = true
mythicmetals = true
cinderscapes = true
edenring = true
farmersdelight = true
bountiful = true
nears = true
barteringstation = true
alloy_forgery = true
chubbystuff = true
wondrouswilds = true
betternether = true
mythicmounts = true
eldritch_mobs = true
brewinandchewin = true
galosphere = true
mcsa = true
betterend = true
another_furniture = true
friendsandfoes = true
twigs = true
ecologics = true
dramaticdoors = true
mythicupgrades = true
snowyspirit = true
enhancedcelestials = true
duckling = true
yigd = true
nethersdelight = true
origins = true
things = true
mythicmetals_decorations = true
byg = true
the_bumblezone = true
conjuring = true
dehydration = true
ftbquests = true
snowrealmagic = true
creatures_from_the_snow = true
sod = true
bewitchment = true
xps_additions = true
charm = true
graveyard = true
customportalapi = true
naturalist = true
supplementaries = true
minecells = true
winterly = true
magnumtorch = true
mantori = true
terrestria = true
quartzelv = true
deeperdarker = true
culturaldelights = true
endrem = true
biomemakeover = true
geodes = true
woof = true
windchimes = true
seasons = true
goodall = true
soulsweapons = true
rottencreatures = true
arcanus = true
xps = true
plushies = true
architects_palette = true
minecraft = true
philipsruins = true
fwaystones = true
archon = true
whisperwoods = true
immersive_weathering = true
voidz = true
endgoblintraders = true
travelersbackpack = true
twilightforest = true
bwplus = true
tradingpost = true
bosses_of_mass_destruction = true
adventurez = true
decorative_blocks = true
dragonloot = true
besmirchment = true
rocks = true
paradise_lost = true
probablychests = true
vinery = true
gofish = true
toms_storage = true
netherdepthsupgrade = true
expandeddelight = true
mysticaloaktree = true
everycomp = true
